In [1]:
import pandas as pd
import numpy as np
import requests
import re
from bs4 import BeautifulSoup

In [2]:
binaaz=pd.DataFrame()

In [3]:
for page_num in range(1,10): 
    url=f'https://bina.az/items/all?page={page_num}'

    page=requests.get(url)

    hmtl=BeautifulSoup(page.content, 'html.parser')

    bina=hmtl.find_all('div', class_='card_params')

    for i in range(len(bina)):
        info=re.sub('<[^>]+>', ' ', str(bina[i])).split('   ')
        if '/gün' in str(info):
            saletype='Günlük'
        elif '/ay' in str(info):
            saletype='Ayliq'
        else:
            saletype='Umumi'

        price= info[1].replace('AZN', '').replace(' ', '')

        location=info[2].strip()

        city=info[4].split(',')[0].strip()

        date=info[4].split(',')[1].strip()

        if info[3].count(' ')==7:
            room_count=info[3].split('  ')[0]
            kvm=info[3].split('  ')[1]
            floor=info[3].split('  ')[2]
        elif info[3].count(' ')==4:
            room_count=info[3].split('  ')[0]
            kvm=info[3].split('  ')[1]
        else:
            kvm=info[3]
        binaaz=binaaz.append({
            'Sale_Type':saletype,
            'Price': price,
            'Location': location,
            'City': city,
            'Rooms_count': room_count,
            'KvM': kvm,
            'Floor': floor,
            'Date': date
        }, ignore_index=True)

In [4]:
binaaz

,Sale_Type,Price,Location,City,Rooms_count,KvM,Floor,Date
0,Umumi,285000,Şah İsmayıl Xətai m.,Bakı,5 otaqlı,227 m²,16/24 mərtəbə,bugün 16:03
1,Umumi,111000,Nizami r.,Bakı,2 otaqlı,76 m²,2/6 mərtəbə,bugün 16:03
2,Umumi,164000,Həzi Aslanov q.,Bakı,3 otaqlı,120 m²,5/13 mərtəbə,bugün 16:03
3,Umumi,279000,Şah İsmayıl Xətai m.,Bakı,4 otaqlı,173 m²,12/16 mərtəbə,bugün 16:03
4,Umumi,50000,Qala q.,Bakı,4 otaqlı,12 sot,12/16 mərtəbə,bugün 16:03
...,...,...,...,...,...,...,...,...
211,Umumi,280000,Mərdəkan q.,Bakı,4 otaqlı,170 m²,2/9 mərtəbə,bugün 15:35
212,Umumi,1200000,İnşaatçılar m.,Bakı,4 otaqlı,400 m²,2/9 mərtəbə,bugün 15:35
213,Umumi,3400000,Elmlər Akademiyası m.,Bakı,4 otaqlı,270 m²,2/9 mərtəbə,bugün 15:34
214,Umumi,145000,Gənclik m.,Bakı,3 otaqlı,70 m²,9/9 mərtəbə,bugün 15:34
215,Umumi,1350000,Xəzər r.,Bakı,3 otaqlı,500 m²,9/9 mərtəbə,bugün 15:34